Update install scripts and move settings to ~/.config
(addresses #55)

diff --git a/linux/install b/linux/install
--- a/linux/install
+++ b/linux/install
@@ -2,7 +2,6 @@
 #
 # Usage: ./install [640 480]
 # Dev47Apps.com
-# functions in install_shell_func_and_conf
 #
 set -e
 
@@ -10,6 +9,7 @@ REPO_PATH="$(/usr/bin/dirname $([ -L $0 ] && /bin/readlink -f $0 || echo $0))"
 source "${REPO_PATH}/install.common"
 
 check_module_options "$1" "$2"
+check_if_loaded
 
 echo "Building $V4L2_LOOPBACK_KO"
 make -C $V4L2_LOOPBACK_DIR
@@ -27,24 +27,42 @@ if mokutil --sb-state | grep -qF enabled; then
 	if [[ ! -e "$PRIV" || ! -e "$PUB" ]]
 	then
 		echo "please specify signing key location (or leave empty to sign manually later)"
+		echo "You can Google 'secure boot' for your distro"
 		echo ""
 		read -rp "Enter the path of the public key: " PUB
 		read -rp "Enter the path of the private key: " PRIV
 	fi
 
+
+	SIGNER_BIN="/usr/src/linux-headers-`uname -r`/scripts/sign-file"
+	[ -e "SIGNER_BIN"  ] || SIGNER_BIN="kmodsign"
 	if [[ -e "$PRIV" && -e "$PUB" ]]
 	then
-		kmodsign sha512 "$PRIV" "$PUB" "$V4L2_LOOPBACK_DIR/$V4L2_LOOPBACK_KO" \
+		$SIGNER_BIN sha512 "$PRIV" "$PUB" "$V4L2_LOOPBACK_DIR/$V4L2_LOOPBACK_KO" \
 			|| echo "warning: device signing failed."
 	fi
 fi
 
-echo "Moving driver and executable to system folders"
-if [ ! -e $DRIVER_LOCATION ]
-then
-	mkdir -p $DRIVER_LOCATION
+if [ -z "$SUDO_USER" ]; then
+	USER_HOME=~
+else
+	USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
 fi
 
+[ -d /opt ]               || mkdir -p /opt
+[ -d $DRIVER_LOCATION ]   || mkdir -p $DRIVER_LOCATION
+[ -d "$USER_HOME/.config" ] || mkdir -p "$USER_HOME/.config"
+
+# remove old settings
+if [ -f "$USER_HOME/.droidcam/settings" ]; then
+	mv "$USER_HOME/.droidcam/settings" "$USER_HOME/.config/droidcam"
+	rm -rf "$USER_HOME/.droidcam"
+fi
+
+echo "Adding uninstall script"
+cp uninstall /opt/droidcam-uninstall
+
+echo "Moving driver and executable to system folders"
 set -x
 cp "$V4L2_LOOPBACK_DIR/$V4L2_LOOPBACK_KO" $DRIVER_LOCATION
 cp droidcam /usr/bin/
@@ -53,16 +71,11 @@ set +x
 
 echo "Registering webcam device"
 modprobe videodev
-insmod $DRIVER_LOCATION$V4L2_LOOPBACK_KO width=$WIDTH height=$HEIGHT || echo "warning: device not registered"
+insmod $DRIVER_LOCATION$V4L2_LOOPBACK_KO width=$WIDTH height=$HEIGHT || echo "warning: insmod failed"
 
 echo "Running depmod"
 depmod -a
 make -C $V4L2_LOOPBACK_DIR clean
-
-echo "Adding uninstall script"
-mkdir -p /opt || true
-cp uninstall /opt/droidcam-uninstall
-
 
 create_v4l2loopback_dc_conf
 register_module_at_boot_time
